version: 2.1

defaults: &defaults
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:
  Hello-World:
    <<: *defaults
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  I-Have-Code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Code has arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

  Run-With-Node:
    <<: *defaults
    steps:
      - run:
          name: Running in a unique container
          command: node -v

  Now-Complete:
    <<: *defaults
    steps:
      - run:
          name: Approval Complete
          command: echo 'Do work once the approval has completed'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - Run-With-Node:
          requires:
            - Hello-World
      - Hold-For-Approval:
          type: approval
          requires:
            - Run-With-Node
            - I-Have-Code
      - Now-Complete:
          requires:
            - Hold-For-Approval
