version: '2.1'

orbs:
  terraform: circleci/terraform@1.1.0

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
      - terraform/plan:
      - terraform/apply:
      - terraform/destroy:
    working_directory: ~/src

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle